# Generated by Django 5.1.6 on 2025-04-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cart_and_orders_app",
            "0002_order_razorpay_order_id_order_razorpay_payment_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("YEARLY", "Yearly"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
