# Generated by Django 5.1.6 on 2025-03-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders_app', '0003_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='COD', max_length=20),
        ),
    ]
