# Generated by Django 5.1.6 on 2025-04-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_and_orders_app", "0003_salesreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="applied_offer",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="applied_offer",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
