# Generated by Django 5.1.6 on 2025-03-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders_app', '0004_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('CARD', 'Credit/Debit Card'), ('WALLET', 'Wallet')], default='COD', max_length=20),
        ),
    ]
