# Generated by Django 5.1.6 on 2025-04-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cart_and_orders_app",
            "0005_alter_cartitem_applied_offer_alter_cartitem_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="wallet_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Amount paid from wallet",
                max_digits=10,
            ),
        ),
    ]
