# Generated by Django 5.1.6 on 2025-04-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart_and_orders_app", "0006_order_wallet_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="wallet_amount",
        ),
    ]
