# Generated by Django 5.1.6 on 2025-03-12 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders_app', '0006_wishlist_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='added_at',
        ),
    ]
