# Generated by Django 5.1.6 on 2025-03-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders_app', '0008_wishlist_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
    ]
