# Generated by Django 5.1.6 on 2025-04-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cart_and_orders_app",
            "0008_order_payment_status_alter_cartitem_applied_offer_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_status",
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="applied_offer",
            field=models.CharField(
                blank=True,
                help_text="Type of offer applied (product/category)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="CancellationRequest",
        ),
    ]
