# Generated by Django 5.1.6 on 2025-04-18 11:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_and_orders_app", "0009_remove_order_payment_status_and_more"),
        ("offer_and_coupon_app", "0028_alter_wallettransaction_transaction_type"),
        ("user_app", "0003_address_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderCancellation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "cancelled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "refunded_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_id"], name="cart_and_or_order_i_be5043_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user"], name="cart_and_or_user_id_83f3b4_idx"),
        ),
        migrations.AddField(
            model_name="ordercancellation",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cancellations",
                to="cart_and_orders_app.orderitem",
            ),
        ),
        migrations.AddField(
            model_name="ordercancellation",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cancellations",
                to="cart_and_orders_app.order",
            ),
        ),
        migrations.AddIndex(
            model_name="ordercancellation",
            index=models.Index(fields=["order"], name="cart_and_or_order_i_8e1b23_idx"),
        ),
    ]
