# Generated by Django 5.1.6 on 2025-04-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart_and_orders_app", "0011_alter_wishlist_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cart_items",
        ),
    ]
