# Generated by Django 5.1.6 on 2025-04-30 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart_and_orders_app", "0012_remove_order_cart_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="applied_offer",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="price",
        ),
    ]
