# Generated by Django 5.1.6 on 2025-05-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "cart_and_orders_app",
            "0013_remove_cartitem_applied_offer_remove_cartitem_price",
        ),
    ]

    operations = []
