# Generated by Django 5.1.6 on 2025-05-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart_and_orders_app", "0015_auto_20250501_2045"),
    ]

    operations = []
