# Generated by Django 5.1.6 on 2025-05-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_and_orders_app", "0016_auto_20250501_2058"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="discount_amount",
            new_name="coupon_discount",
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="items",
            field=models.ManyToManyField(
                blank=True,
                related_name="return_requests",
                to="cart_and_orders_app.orderitem",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Shipped", "Shipped"),
                    ("Out for Delivery", "Out for Delivery"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
