# Generated by Django 5.1.6 on 2025-05-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cart_and_orders_app",
            "0017_rename_discount_amount_order_coupon_discount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ordercancellation",
            name="product_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the product at cancellation",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ordercancellation",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="Quantity cancelled"
            ),
        ),
        migrations.AddField(
            model_name="ordercancellation",
            name="variant_flavor",
            field=models.CharField(
                blank=True,
                help_text="Flavor of the variant at cancellation",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ordercancellation",
            name="variant_size_weight",
            field=models.CharField(
                blank=True,
                help_text="Size/weight of the variant at cancellation",
                max_length=50,
                null=True,
            ),
        ),
    ]
