# Generated by Django 5.1.6 on 2025-05-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_and_orders_app", "0018_ordercancellation_product_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="address_country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="address_full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="address_line1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="address_line2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="address_phone",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="address_postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="address_state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
