# Generated by Django 5.1.6 on 2025-04-06 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_and_orders_app", "0001_initial"),
        ("offer_and_coupon_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercoupon",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cart_and_orders_app.order",
            ),
        ),
    ]
