# Generated by Django 5.1.6 on 2025-03-15 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders_app', '0010_cartitem_price'),
        ('offer_and_coupon_app', '0001_initial'),
        ('product_app', '0012_alter_tag_unique_together_alter_tag_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at'], 'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
        migrations.AlterModelOptions(
            name='usercoupon',
            options={'ordering': ['-used_at', '-id'], 'verbose_name': 'User Coupon', 'verbose_name_plural': 'User Coupons'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, help_text='Products this coupon applies to (leave blank for all products)', related_name='offer_coupons', to='product_app.product'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(db_index=True, help_text='Unique coupon code (e.g., SAVE200, SAVE300)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='Fixed discount amount (e.g., 200.00, 300.00)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the coupon is currently active'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minimum_order_amount',
            field=models.DecimalField(decimal_places=2, help_text='Minimum order total to apply this coupon (e.g., 3999.00, 5999.00)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the coupon has been used'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of uses (0 for unlimited)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(help_text='Start date and time when the coupon becomes valid'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(help_text='End date and time when the coupon expires'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='coupon',
            field=models.ForeignKey(help_text='Associated coupon', on_delete=django.db.models.deletion.CASCADE, related_name='user_usages', to='offer_and_coupon_app.coupon'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Whether the coupon has been used by this user'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order in which the coupon was applied', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart_and_orders_app.order'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='used_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the coupon was used', null=True),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='user',
            field=models.ForeignKey(help_text='User who can use or has used this coupon', on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
