# Generated by Django 5.1.6 on 2025-03-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_and_coupon_app', '0002_alter_coupon_options_alter_usercoupon_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_value',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed discount amount (e.g., 200.00, 300.00)', max_digits=10),
        ),
    ]
