# Generated by Django 5.1.6 on 2025-04-10 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer_and_coupon_app", "0004_alter_categoryoffer_discount_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryoffer",
            name="discount_type",
        ),
        migrations.RemoveField(
            model_name="productoffer",
            name="discount_type",
        ),
        migrations.AlterField(
            model_name="categoryoffer",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Percentage discount (0.01-100)",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="productoffer",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Percentage discount (0.01-100)",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
    ]
