# Generated by Django 5.1.6 on 2025-04-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer_and_coupon_app", "0005_remove_categoryoffer_discount_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="applicable_products",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="discount_amount",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="coupon",
            name="discount_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(),
        ),
    ]
