# Generated by Django 5.1.6 on 2025-03-16 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_and_coupon_app', '0006_alter_coupon_applicable_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer_and_coupon_app.coupon'),
        ),
    ]
