# Generated by Django 5.1.6 on 2025-04-13 13:41

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer_and_coupon_app", "0006_remove_coupon_applicable_products_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Discount percentage (0.01-100)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="minimum_order_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 13, 13, 41, 41, 911222, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
