# Generated by Django 5.1.6 on 2025-03-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_and_coupon_app', '0007_alter_usercoupon_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_active',
        ),
    ]
