# Generated by Django 5.1.6 on 2025-04-13 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer_and_coupon_app", "0007_alter_coupon_discount_percentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 13, 13, 41, 47, 395346, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
