# Generated by Django 5.1.6 on 2025-04-14 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer_and_coupon_app", "0012_alter_coupon_valid_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 14, 5, 10, 34, 600769, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
