# Generated by Django 5.1.6 on 2025-04-16 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer_and_coupon_app", "0019_alter_coupon_valid_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 16, 14, 11, 16, 522496, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
