# Generated by Django 5.1.6 on 2025-04-17 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer_and_coupon_app", "0023_alter_coupon_valid_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 17, 15, 46, 27, 208089, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
