# Generated by Django 5.1.6 on 2025-04-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer_and_coupon_app", "0027_alter_coupon_valid_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("CREDIT", "Credit"),
                    ("DEBIT", "Debit"),
                    ("REFUND", "Refund"),
                ],
                max_length=6,
            ),
        ),
    ]
