# Generated by Django 5.1.6 on 2025-04-19 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "offer_and_coupon_app",
            "0030_remove_categoryoffer_apply_to_subcategories_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 19, 15, 34, 49, 757109, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
