# Generated by Django 5.1.6 on 2025-04-22 12:25

import datetime
from django.db import migrations, models
import django.utils.timezone

def default_valid_to():
    return django.utils.timezone.now() + datetime.timedelta(days=30)

class Migration(migrations.Migration):

    dependencies = [
        ("offer_and_coupon_app", "0038_alter_coupon_valid_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(default=default_valid_to),
        ),
    ]
