# Generated by Django 5.1.6 on 2025-04-22 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer_and_coupon_app", "0039_alter_coupon_valid_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 22, 12, 35, 36, 516205, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
