# Generated by Django 5.1.6 on 2025-04-22 12:53

import offer_and_coupon_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer_and_coupon_app", "0040_alter_coupon_valid_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(
                default=offer_and_coupon_app.models.default_valid_to
            ),
        ),
    ]
