# Generated by Django 5.1.6 on 2025-04-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer_and_coupon_app", "0042_alter_wallettransaction_transaction_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productoffer",
            name="products",
        ),
        migrations.RemoveField(
            model_name="referral",
            name="coupon",
        ),
        migrations.RemoveField(
            model_name="referral",
            name="referred_user",
        ),
        migrations.RemoveField(
            model_name="referral",
            name="referrer",
        ),
        migrations.RemoveField(
            model_name="referralcode",
            name="user",
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("CREDIT", "Credit"),
                    ("DEBIT", "Debit"),
                    ("REFUND", "Refund"),
                ],
                max_length=9,
            ),
        ),
        migrations.DeleteModel(
            name="CategoryOffer",
        ),
        migrations.DeleteModel(
            name="ProductOffer",
        ),
        migrations.DeleteModel(
            name="Referral",
        ),
        migrations.DeleteModel(
            name="ReferralCode",
        ),
    ]
