# Generated by Django 5.1.6 on 2025-04-27 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "offer_and_coupon_app",
            "0043_remove_productoffer_products_remove_referral_coupon_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="max_discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Maximum discount amount (0 means no cap)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
