# Generated by Django 5.1.6 on 2025-04-27 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offer_and_coupon_app", "0044_coupon_max_discount_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="max_discount_amount",
        ),
    ]
