# Generated by Django 5.1.6 on 2025-04-27 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer_and_coupon_app", "0045_remove_coupon_max_discount_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="usage_count",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="usage_limit",
        ),
        migrations.AddField(
            model_name="coupon",
            name="max_discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Maximum discount amount (0 means no cap)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Discount percentage (0.01-50)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(50.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="minimum_order_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Minimum order amount required to apply the coupon",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
