# Generated by Django 5.1.6 on 2025-05-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offer_and_coupon_app", "0047_alter_usercoupon_coupon"),
    ]

    operations = []
