# Generated by Django 5.1.6 on 2025-04-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="long_description",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="short_description",
        ),
    ]
