# Generated by Django 5.1.6 on 2025-04-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0002_rename_long_description_product_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="expiry_date",
        ),
    ]
