# Generated by Django 5.1.6 on 2025-04-07 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0003_remove_productvariant_expiry_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="average_rating",
        ),
    ]
