# Generated by Django 5.1.6 on 2025-04-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0004_remove_product_average_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
