# Generated by Django 5.1.6 on 2025-04-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0005_product_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
