# Generated by Django 5.1.6 on 2025-04-13 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0006_remove_product_is_deleted_category_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="category",
            name="is_deleted",
        ),
    ]
