# Generated by Django 5.1.6 on 2025-03-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_product_is_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_listed',
        ),
    ]
