# Generated by Django 5.1.6 on 2025-04-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0007_remove_brand_is_deleted_remove_category_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="average_rating",
            field=models.FloatField(default=0.0),
        ),
    ]
