# Generated by Django 5.1.6 on 2025-04-24 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0008_product_average_rating"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="discount_percentage",
        ),
        migrations.RemoveField(
            model_name="review",
            name="helpful_votes",
        ),
        migrations.AddField(
            model_name="category",
            name="offer_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Offer percentage for all products in this category",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="offer_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="Product-specific offer percentage",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
    ]
