# Generated by Django 5.1.6 on 2025-04-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0009_alter_category_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="average_rating",
        ),
    ]
