# Generated by Django 5.1.6 on 2025-04-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0010_remove_product_average_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="average_rating",
            field=models.FloatField(default=0.0),
        ),
    ]
