# Generated by Django 5.1.6 on 2025-05-03 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0011_product_average_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="average_rating",
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(
                help_text="Rating from 1 to 5 stars",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
