# Generated by Django 5.1.6 on 2025-04-17 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0002_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be a valid 10-digit number starting with 6-9.",
                        regex="^[6-9]\\d{9}$",
                    )
                ],
            ),
        ),
    ]
