# Generated by Django 5.1.6 on 2025-03-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_userprofile_address_line1_userprofile_address_line2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_blocked',
        ),
    ]
