# Generated by Django 5.1.6 on 2025-04-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_address_phone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LoginAttempt",
        ),
    ]
