# Generated by Django 5.1.6 on 2025-05-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0006_remove_customuser_is_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
