# Generated by Django 5.1.6 on 2025-05-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0008_customuser_referral_code_referral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="referral_code",
            field=models.CharField(
                blank=True, default=None, max_length=10, unique=True
            ),
        ),
    ]
