# Generated by Django 5.1.6 on 2025-03-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_customuser_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='wallet',
        ),
    ]
