# Generated by Django 5.1.6 on 2025-05-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0009_alter_customuser_referral_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="referral_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
