# Generated by Django 5.1.6 on 2025-05-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0010_alter_customuser_referral_code"),
        ("user_app", "0011_populate_referral_codes"),
    ]

    operations = []
