# Generated by Django 5.1.6 on 2025-03-19 01:19

import django.core.validators
import user_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_remove_customuser_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, help_text='Enter your full name (first and last name)', max_length=255, null=True, validators=[user_app.models.validate_full_name]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, error_messages={'unique': 'This phone number is already registered.'}, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit number starting with 6-9.', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
