# Generated by Django 5.1.6 on 2025-05-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0012_merge_20250506_2040"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="referral_code",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
