# Generated by Django 5.1.6 on 2025-03-19 02:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_alter_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(db_index=True, error_messages={'unique': 'This username is already taken.'}, max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username can only contain letters, numbers, dots and underscores', regex='^[a-zA-Z0-9._]+$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
