# Generated by Django 5.1.6 on 2025-05-07 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0013_alter_customuser_referral_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="address_line1",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="address_line2",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="state",
        ),
    ]
