# Generated by Django 5.1.6 on 2025-05-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0014_remove_userprofile_address_line1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="referral_code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
